// Fix: Create level data file to provide structured data for game levels.
import { Level } from '../types';

export const LEVELS: Level[] = [
  {
    id: 1,
    name: "Pig Pen",
    backgroundColor: "bg-gradient-to-b from-green-400 to-green-600",
    enemies: [
      { radius: 30, score: 100, emoji: "🐷" },
      { radius: 40, score: 150, emoji: "🐷" },
      { radius: 35, score: 120, emoji: "👹" },
      { radius: 25, score: 150, emoji: "🎯" },
    ],
  },
  {
    id: 2,
    name: "Robot Ruckus",
    backgroundColor: "bg-gradient-to-b from-gray-500 to-gray-700",
    enemies: [
      { radius: 30, score: 100, emoji: "🤖" },
      { radius: 45, score: 200, emoji: "👾" },
      { radius: 35, score: 120, emoji: "🤖" },
      { radius: 40, score: 150, emoji: "👹" },
      { radius: 35, score: 130, emoji: "👻" },
    ],
  },
  {
    id: 3,
    name: "Alien Invasion",
    backgroundColor: "bg-gradient-to-b from-indigo-900 via-purple-900 to-black",
    enemies: [
        { radius: 50, score: 250, emoji: "👹" },
        { radius: 40, score: 150, emoji: "👾" },
        { radius: 45, score: 200, emoji: "👾" },
        { radius: 30, score: 100, emoji: "🤖" },
        { radius: 35, score: 120, emoji: "🐷" },
        { radius: 40, score: 160, emoji: "💀" },
    ],
  },
  {
    id: 4,
    name: "Spooky Specters",
    backgroundColor: "bg-gradient-to-b from-gray-900 via-purple-900 to-black",
    enemies: [
      { radius: 35, score: 130, emoji: "👻" },
      { radius: 40, score: 160, emoji: "💀" },
      { radius: 35, score: 130, emoji: "👻" },
      { radius: 45, score: 200, emoji: "👹" },
      { radius: 30, score: 100, emoji: "🐷" },
      { radius: 30, score: 110, emoji: "🤡" },
    ],
  },
  {
    id: 5,
    name: "Circus of Chaos",
    backgroundColor: "bg-gradient-to-b from-red-500 via-pink-500 to-purple-600",
    enemies: [
      { radius: 30, score: 110, emoji: "🤡" },
      { radius: 25, score: 150, emoji: "🎯" },
      { radius: 30, score: 110, emoji: "🤡" },
      { radius: 25, score: 150, emoji: "🎯" },
      { radius: 40, score: 180, emoji: "👻" },
      { radius: 50, score: 250, emoji: "👹" },
      { radius: 45, score: 200, emoji: "👾" },
    ],
  },
  {
    id: 6,
    name: "Ghostly Gauntlet",
    backgroundColor: "bg-gradient-to-b from-slate-800 to-slate-900",
    enemies: [
      { radius: 35, score: 130, emoji: "👻" },
      { radius: 35, score: 130, emoji: "👻" },
      { radius: 40, score: 160, emoji: "💀" },
      { radius: 40, score: 160, emoji: "💀" },
      { radius: 35, score: 130, emoji: "👻" },
      { radius: 35, score: 130, emoji: "👻" },
    ],
  },
  {
    id: 7,
    name: "Target Practice",
    backgroundColor: "bg-gradient-to-b from-sky-400 to-sky-600",
    enemies: [
      { radius: 25, score: 150, emoji: "🎯" },
      { radius: 25, score: 150, emoji: "🎯" },
      { radius: 25, score: 150, emoji: "🎯" },
      { radius: 25, score: 150, emoji: "🎯" },
      { radius: 25, score: 150, emoji: "🎯" },
      { radius: 25, score: 150, emoji: "🎯" },
      { radius: 40, score: 150, emoji: "🐷" },
    ],
  },
  {
    id: 8,
    name: "Clown Town",
    backgroundColor: "bg-gradient-to-b from-pink-400 to-purple-500",
    enemies: [
      { radius: 30, score: 110, emoji: "🤡" },
      { radius: 30, score: 110, emoji: "🤡" },
      { radius: 30, score: 110, emoji: "🤡" },
      { radius: 50, score: 250, emoji: "👹" },
      { radius: 50, score: 250, emoji: "👹" },
    ],
  },
  {
    id: 9,
    name: "Mechanic's Menace",
    backgroundColor: "bg-gradient-to-b from-orange-400 to-red-600",
    enemies: [
      { radius: 30, score: 100, emoji: "🤖" },
      { radius: 30, score: 100, emoji: "🤖" },
      { radius: 40, score: 160, emoji: "💀" },
      { radius: 45, score: 200, emoji: "👾" },
      { radius: 45, score: 200, emoji: "👾" },
      { radius: 40, score: 160, emoji: "💀" },
    ],
  },
  {
    id: 10,
    name: "Final Boss",
    backgroundColor: "bg-gradient-to-b from-red-800 via-black to-black",
    enemies: [
      { radius: 60, score: 500, emoji: "👹" },
      { radius: 30, score: 110, emoji: "🤡" },
      { radius: 30, score: 110, emoji: "🤡" },
      { radius: 35, score: 130, emoji: "👻" },
      { radius: 35, score: 130, emoji: "👻" },
      { radius: 25, score: 150, emoji: "🎯" },
      { radius: 25, score: 150, emoji: "🎯" },
    ],
  },
];