// Fix: Corrected import path for PokemonType.
import { PokemonType } from "../types";

export const POKEMON_DATA: Record<string, { name: string; types: PokemonType[] }> = {
    // Starters & Popular
    '🍃': { name: "Bulbasaur", types: [PokemonType.Grass, PokemonType.Poison] },
    '🔥': { name: "Charmander", types: [PokemonType.Fire] },
    '💧': { name: "Squirtle", types: [PokemonType.Water] },
    '⚡': { name: "Pikachu", types: [PokemonType.Electric] },
    '🐭': { name: "Rattata", types: [PokemonType.Normal] },
    '🐛': { name: "Caterpie", types: [PokemonType.Bug] },
    '🐦': { name: "Pidgey", types: [PokemonType.Normal, PokemonType.Flying] },
    '👻': { name: "Gastly", types: [PokemonType.Ghost, PokemonType.Poison] },
    '🪨': { name: "Geodude", types: [PokemonType.Rock, PokemonType.Ground] },
    '❄️': { name: "Articuno", types: [PokemonType.Ice, PokemonType.Flying] },
    '🐉': { name: "Dratini", types: [PokemonType.Dragon] },
    'PSY': { name: "Mewtwo", types: [PokemonType.Psychic] },

    // Animals
    '🐸': { name: "Poliwag", types: [PokemonType.Water] },
    '🐷': { name: "Tepig", types: [PokemonType.Fire] },
    '🐵': { name: "Mankey", types: [PokemonType.Fighting] },
    '🐶': { name: "Growlithe", types: [PokemonType.Fire] },
    '🐱': { name: "Meowth", types: [PokemonType.Normal] },
    '🦊': { name: "Vulpix", types: [PokemonType.Fire] },
    '🐻': { name: "Teddiursa", types: [PokemonType.Normal] },
    '🐼': { name: "Pancham", types: [PokemonType.Fighting] },
    '🦁': { name: "Litleo", types: [PokemonType.Fire, PokemonType.Normal] },
    '🐯': { name: "Incineroar", types: [PokemonType.Fire, PokemonType.Dark] },
    '🦄': { name: "Galarian Rapidash", types: [PokemonType.Psychic, PokemonType.Fairy] },
    '🐮': { name: "Miltank", types: [PokemonType.Normal] },
    '🐔': { name: "Torchic", types: [PokemonType.Fire] },
    '🐧': { name: "Piplup", types: [PokemonType.Water] },
    '🦉': { name: "Hoothoot", types: [PokemonType.Normal, PokemonType.Flying] },
    '🦇': { name: "Zubat", types: [PokemonType.Poison, PokemonType.Flying] },
    '🕷️': { name: "Spinarak", types: [PokemonType.Bug, PokemonType.Poison] },
    '🐢': { name: "Turtwig", types: [PokemonType.Grass] },
    '🐍': { name: "Ekans", types: [PokemonType.Poison] },
    '🦕': { name: "Aurorus", types: [PokemonType.Rock, PokemonType.Ice] },
    '🦖': { name: "Tyrantrum", types: [PokemonType.Rock, PokemonType.Dragon] },
    '🐙': { name: "Octillery", types: [PokemonType.Water] },
    '🦀': { name: "Krabby", types: [PokemonType.Water] },
    '🦐': { name: "Clauncher", types: [PokemonType.Water] },
    '🐟': { name: "Magikarp", types: [PokemonType.Water] },
    '🐝': { name: "Beedrill", types: [PokemonType.Bug, PokemonType.Poison] },
    '🦋': { name: "Butterfree", types: [PokemonType.Bug, PokemonType.Flying] },

    // Plants & Food
    '🌸': { name: "Cherrim", types: [PokemonType.Grass] },
    '🌲': { name: "Sudowoodo", types: [PokemonType.Rock] },
    '🌳': { name: "Trevenant", types: [PokemonType.Ghost, PokemonType.Grass] },
    '🌴': { name: "Exeggutor", types: [PokemonType.Grass, PokemonType.Psychic] },
    '🌵': { name: "Maractus", types: [PokemonType.Grass] },
    '🍄': { name: "Amoonguss", types: [PokemonType.Grass, PokemonType.Poison] },
    '🍎': { name: "Applin", types: [PokemonType.Grass, PokemonType.Dragon] },
    '🍓': { name: "Bounsweet", types: [PokemonType.Grass] },
    '🍒': { name: "Cherubi", types: [PokemonType.Grass] },
    '🥥': { name: "Exeggcute", types: [PokemonType.Grass, PokemonType.Psychic] },
    '🥚': { name: "Exeggcute", types: [PokemonType.Grass, PokemonType.Psychic] },
    '🍦': { name: "Vanillite", types: [PokemonType.Ice] },
    '🎂': { name: "Alcremie", types: [PokemonType.Fairy] },
    '☕': { name: "Sinistea", types: [PokemonType.Ghost] },

    // Objects & Symbols
    '💣': { name: "Voltorb", types: [PokemonType.Electric] },
    '🛡️': { name: "Bastiodon", types: [PokemonType.Rock, PokemonType.Steel] },
    '⚙️': { name: "Klink", types: [PokemonType.Steel] },
    '💎': { name: "Carbink", types: [PokemonType.Rock, PokemonType.Fairy] },
    '💰': { name: "Gimmighoul", types: [PokemonType.Ghost] },
    '🪙': { name: "Gimmighoul", types: [PokemonType.Ghost] },
    '⚔️': { name: "Honedge", types: [PokemonType.Steel, PokemonType.Ghost] },
    '💀': { name: "Duskull", types: [PokemonType.Ghost] },
    '🤖': { name: "Magnezone", types: [PokemonType.Electric, PokemonType.Steel] },
    '🛸': { name: "Magnezone", types: [PokemonType.Electric, PokemonType.Steel] },
    '👾': { name: "Deoxys", types: [PokemonType.Psychic] },
    '🏰': { name: "Palossand", types: [PokemonType.Ghost, PokemonType.Ground] },
    '🗿': { name: "Nosepass", types: [PokemonType.Rock] },
    '🧱': { name: "Stonjourner", types: [PokemonType.Rock] },
    '❤️': { name: "Luvdisc", types: [PokemonType.Water] },
    '⭐': { name: "Staryu", types: [PokemonType.Water] },
    '🌙': { name: "Lunatone", types: [PokemonType.Rock, PokemonType.Psychic] },
    '☀️': { name: "Solrock", types: [PokemonType.Rock, PokemonType.Psychic] },
    '🌈': { name: "Ho-Oh", types: [PokemonType.Fire, PokemonType.Flying] },
    '🌊': { name: "Gyarados", types: [PokemonType.Water, PokemonType.Flying] },
    
    // People-like
    '🥷': { name: "Greninja", types: [PokemonType.Water, PokemonType.Dark] },
    '👨‍🚀': { name: "Beheeyem", types: [PokemonType.Psychic] },
    '🎅': { name: "Delibird", types: [PokemonType.Ice, PokemonType.Flying] },
    '👮': { name: "Arcanine", types: [PokemonType.Fire] },
    '🥊': { name: "Hitmonchan", types: [PokemonType.Fighting] },
    '🥋': { name: "Sawk", types: [PokemonType.Fighting] },
    '🤠': { name: "Cacturne", types: [PokemonType.Grass, PokemonType.Dark] },

    // Catch-all for others
    '👹': { name: "Incineroar", types: [PokemonType.Fire, PokemonType.Dark] },
};
